title: Hi all! I'm Shafanda Nabil Sembodo # your name (or website title) here
logo: "/images/photo_profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Accomplished data scientist with more than three years of relevant experience in oil & gas,
  education, and healthcare applications. Proficient in data analysis, data mining, and artificial
  intelligence. Certified by IBM as a Data Science Practitioner, skilled in transforming raw data into
  actionable insights to make informed decisions and drive business growth.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
